### PR TITLE
Fixes after integration review (#420)

### LINKED ISSUE #420: Fixes after integration review

### PR DESCRIPTION
**Pull request by cdesquilbet-dila**
Closes #420

### CODE REVIEW

File: public/mobile-app/src/routes/notifications/+page.svelte [hunk 1]
```diff
@@ -28,16 +28,24 @@
...
-    <a href="/" title="Retour à la page d'accueil" aria-label="Retour à la page d'accueil">
+  <div class="back-button-wrapper">
+    <button onclick={navigateToPreviousPage}
+            title="Retour à la page précédente"
+            aria-label="Retour à la page précédente"
+            data-testid="back-button"
+    >
       <span aria-hidden="true" class="fr-icon-arrow-left-line"></span>
-    </a>
+    </button>
```
Comment (magopian) [inline public/mobile-app/src/routes/notifications/+page.svelte]: Could this also be a `<BackButton />`?

File: public/mobile-app/src/routes/procedure/+page.svelte [hunk 2]
```diff
@@ -31,14 +31,22 @@
...
+  <nav>
+    <div class="back-button-wrapper">
+      <button onclick={navigateToPreviousPage}
+              title="Retour à la page précédente"
+              aria-label="Retour à la page précédente"
+              data-testid="back-button"
+      >
         <span aria-hidden="true" class="fr-icon-arrow-left-line"></span>
-      </a>
+      </button>
```
Comment (magopian) [inline public/mobile-app/src/routes/procedure/+page.svelte]: Same here, could this be a `<BackButton />`?

**Review by magopian — APPROVED** [review]
Excellent work, thanks for taking the time to list all the fixes with Lucie, and implement them! 💯 🙏 

🚢

File: public/mobile-app/src/lib/components/BackButton.svelte [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+            title="Retour à la page précédente"
+            aria-label="Retour à la page précédente"
+            data-testid="back-button"
+    >
+      <span aria-hidden="true" class="fr-icon-arrow-left-line"></span>
+    </button>
+  </div>
+  <div class="title">
+    <h2>{title}</h2>
+  </div>
```
[the remark this answers is not in the document]
Comment (cdesquilbet-dila) [reply public/mobile-app/src/lib/components/BackButton.svelte]: Yes!

File: public/mobile-app/src/routes/notifications/page.svelte.test.ts [hunk 4]
```diff
@@ -34,6 +34,20 @@ describe('/+page.svelte', () => {
...
+    // When
+    render(Page)
+    const backButton = screen.getByTestId('back-button')
+    await fireEvent.click(backButton)
+
+    // Then
+    expect(backSpy).toHaveBeenCalledTimes(1)
+    backSpy.mockRestore()
+  })
+
```
[the remark this answers is not in the document]
Comment (cdesquilbet-dila) [reply public/mobile-app/src/routes/notifications/page.svelte.test.ts]: Please see https://github.com/numerique-gouv/ami-notifications-api/pull/421#discussion_r2645333211

File: public/mobile-app/src/routes/procedure/+page.svelte (hunk 2 above)
Comment (cdesquilbet-dila) [reply public/mobile-app/src/routes/procedure/+page.svelte]: Please see https://github.com/numerique-gouv/ami-notifications-api/pull/421#discussion_r2645333211
